version: 2

sources : 

    - name: raw
      description: aaaa
      database: steam-data-engineering-gcp
      schema: steam_raw
      tables: 
        - name : steam_spy_scrap
        - name : steam_store_data
        - name : steam_dlc_data
        - name : steam_reviews

    - name: staging
      description: aaa
      database: steam-data-engineering-gcp
      schema: dbt_development
      tables: 
        - name : categories
        - name : genres
        - name : developers
        - name : publishers
        
models: 
  - name: steam_spy_scrap
  - name: steam_store_data
  - name: categories
  - name: developers
  - name: publishers
  - name: genres

  - name: steam_games
    columns:
      - name: appid
        tests:
          - unique
          - not_null

  - name: steam_reviews
    columns: 
      - name: author_steamid
        tests: 
          - not_null
      - name: gameid
        tests: 
          - not_null
      - name: reviewid
        tests: 
          - not_null
          - unique

  - name: steam_dlc_data
    columns:
      - name: appid
        tests:
          - unique
          - not_null