name: Upload Spark script to GCP bucket
on:
  push:
    branches:
    - main

jobs:
  upload_spark_script:
    runs-on: ubuntu-20.04
    permissions:  
      contents: 'read'
      id-token: 'write'

    steps:

    - name: auth
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/146724372394/locations/global/workloadIdentityPools/wif-pool-steam-de/*'
        service_account: 'github-actions@steam-data-engineering-gcp.iam.gserviceaccount.com' 
        
    - name: checkout
      uses: actions/checkout@v2

    - name: check dir  
      run: ls spark/  
    
    - name: upload-file
      uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: 'spark/spark_all_games_reviews.py'
        destination: 'gs://steam-datalake-reviews/'
        
     
